[Distribution]
Distribution=arch
# LocalMirror=file:///var/lib/localmirror

[Output]
Format=uki
# Format=disk

[Include]
Include=mkosi-vm

[Validation]
SecureBoot=false
SecureBootAutoEnroll=false
Sign=false
# Signing artifacts (hashsums etc) using a GPG key:
# Key=D4B58E897A929F2E
# Signing secure boot using PIV on yubikey:
# SecureBoot=true
# SecureBootKey=pkcs11:
# SecureBootCertificate=secureboot.crt

[Content]
Packages=
         pacman
         archlinux-keyring
         amd-ucode
         intel-ucode
#         tpm2-tss
#         libfido2
#         libp11-kit
WithDocs=false
RootPassword=toor
Timezone=Europe/Stockholm
Keymap=sv-latin1
InitrdProfiles=network

[Config]
Profiles=archinstall

[Build]
Incremental=true
ToolsTree=default
ToolsTreeProfiles=devel,misc,package-manager,runtime,gui
WithNetwork=yes

[Runtime]
Console=gui
CPUs=4
RAM=8G
