import argparse
import inspect
import shlex
import subprocess
from enum import Enum
from itertools import product
from pathlib import Path

from archinstall.default_profiles.desktops.plasma import PlasmaFlavor
from archinstall.default_profiles.desktops.utils import SeatAccess
from archinstall.default_profiles.profile import CustomSetting
from archinstall.lib.applications import application_handler
from archinstall.lib.hardware import CPUVendor, GfxPackage
from archinstall.lib.installer import __accessibility_packages__, __packages__
from archinstall.lib.models.application import FontPackage
from archinstall.lib.models.device import FilesystemType
from archinstall.lib.models.package_types import InstallationPackage, Kernel
from archinstall.lib.profile.profiles_handler import ProfileHandler

PROFILE_SETTINGS: dict[CustomSetting, type[Enum]] = {
	CustomSetting.SeatAccess: SeatAccess,
	CustomSetting.PlasmaFlavor: PlasmaFlavor,
}


def package_targets() -> set[str]:
	if set(PROFILE_SETTINGS) != set(CustomSetting):
		raise ValueError('Add missing custom settings to PROFILE_SETTINGS')

	packages = set(__packages__ + __accessibility_packages__)
	for package_enum in (FontPackage, GfxPackage, InstallationPackage):
		packages.update(choice.value for choice in package_enum)
	packages.update(f'{kernel.value}-headers' for kernel in Kernel)
	packages.update(package for fs in FilesystemType if (package := fs.installation_pkg))
	packages.update(ucode.stem for vendor in CPUVendor if (ucode := vendor.get_ucode()))

	for profile in ProfileHandler().profiles:
		original = profile.custom_settings
		packages.update(profile.packages)
		for choices in product(*PROFILE_SETTINGS.values()):
			profile.custom_settings = original | dict(zip(PROFILE_SETTINGS, (choice.value for choice in choices), strict=True))
			packages.update(profile.packages)

	for cls in vars(application_handler).values():
		if inspect.isclass(cls) and cls.__module__.startswith('archinstall.applications.'):
			app = cls()
			for name, member in inspect.getmembers(cls):
				if isinstance(member, property) and (name == 'packages' or name.endswith('_packages')):
					packages.update(getattr(app, name))
	return packages


def pacman(*args: str) -> list[str]:
	return subprocess.run(['pacman', *args], check=True, capture_output=True, text=True).stdout.splitlines()


def repository_groups() -> tuple[set[str], dict[str, set[str]]]:
	names = set(pacman('-Slq'))
	if not names:
		raise ValueError('No package database available; refresh it before generating the inventory')
	groups: dict[str, set[str]] = {}
	for line in pacman('-Sgg'):
		group, package = line.split()
		groups.setdefault(group, set()).add(package)
	return names, groups


def render(targets: set[str], names: set[str], groups: dict[str, set[str]]) -> str:
	selected_groups = (targets & groups.keys()) - names
	direct = targets - selected_groups
	entries = [f'\t{shlex.quote(package)}' for package in sorted(direct)]
	written = set(direct)
	for group in sorted(selected_groups):
		entries.append(f'\t# group: {group}')
		entries.extend(f'\t{shlex.quote(package)}' for package in sorted(groups[group] - written))
		written.update(groups[group])

	dependencies = '\n'.join(entries)
	return f"""# Generated by python -m archinstall.lib.packages.meta

pkgname=archinstall-meta
pkgver=1
pkgrel=1
pkgdesc="Package inventory for archinstall"
arch=(any)
url="https://github.com/archlinux/archinstall"
license=(GPL-3.0-only)
depends=(archinstall)
optdepends=(
{dependencies}
)

package() {{
	:
}}
"""


def main() -> None:
	parser = argparse.ArgumentParser(description='Generate archinstall-meta from the installation code and local package database.')
	parser.add_argument('--check', action='store_true', help='fail if the generated PKGBUILD differs')
	parser.add_argument('--output', type=Path, default=Path(__file__).resolve().parents[3] / 'archinstall-meta/PKGBUILD')
	args = parser.parse_args()
	targets = package_targets()
	names, groups = repository_groups()
	if aliases := sorted(targets - names - groups.keys()):
		pacman('-Spdd', '--noconfirm', '--print-format', '%n', '--', *aliases)
	content = render(targets, names, groups)
	if args.check:
		if args.output.read_text() != content:
			parser.exit(1, 'Run python -m archinstall.lib.packages.meta to update archinstall-meta/PKGBUILD\n')
	else:
		args.output.write_text(content)


if __name__ == '__main__':
	main()
