DEVICE_UNKNOWN: int
PARTITION_NORMAL: int
PARTITION_BOOT: int
PARTITION_ESP: int
PARTITION_BLS_BOOT: int
PARTITION_LINUX_HOME: int
PARTITION_SWAP: int

class IOException(Exception): ...
class DiskException(Exception): ...
class PartitionException(Exception): ...
class Constraint: ...

class Device:
	@property
	def model(self) -> str: ...
	@property
	def path(self) -> str: ...
	@property
	def type(self) -> int: ...
	@property
	def sectorSize(self) -> int: ...
	@property
	def readOnly(self) -> bool: ...
	@property
	def dirty(self) -> bool: ...
	@property
	def optimalAlignedConstraint(self) -> Constraint: ...
	def getLength(self, unit: str = ...) -> int: ...

class Geometry:
	start: int
	end: int

	def __init__(self, device: Device, start: int, length: int) -> None: ...
	@property
	def device(self) -> Device: ...
	def getLength(self, unit: str = ...) -> int: ...

class FileSystem:
	def __init__(
		self,
		type: str,  # pylint: disable=redefined-builtin
		geometry: Geometry,
	) -> None: ...
	@property
	def type(self) -> str: ...

class Disk:
	@property
	def device(self) -> Device: ...
	@property
	def type(self) -> str: ...
	@property
	def partitions(self) -> list[Partition]: ...
	def commit(self) -> None: ...
	def addPartition(self, partition: Partition, constraint: Constraint) -> None: ...
	def deletePartition(self, partition: Partition) -> None: ...
	def getFreeSpaceRegions(self) -> list[Geometry]: ...

class Partition:
	fileSystem: FileSystem | None
	geometry: Geometry
	type: int
	type_uuid: bytes

	def __init__(
		self,
		disk: Disk,
		type: int,  # pylint: disable=redefined-builtin
		fs: FileSystem,
		geometry: Geometry,
	) -> None: ...
	@property
	def disk(self) -> Disk: ...
	@property
	def path(self) -> str: ...
	def get_name(self) -> str: ...
	def getFlag(self, flag: int) -> int: ...
	def setFlag(self, flag: int) -> None: ...
	def getLength(self, unit: str = ...) -> int: ...

def getAllDevices() -> list[Device]: ...
def getDevice(device: str) -> Device: ...
def newDisk(device: Device) -> Disk: ...
def freshDisk(device: Device, label: str) -> Disk: ...

devices: dict[int, str]
