on: [ push, pull_request ]
name: Bandit security checkup
jobs:
    bandit:
        runs-on: ubuntu-latest
        container:
            image: archlinux/archlinux:latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
            - run: pacman --noconfirm -Syu bandit
            - name: Security checkup with Bandit
              run: bandit -r archinstall || exit 0
