on: [ push, pull_request ]
name: ruff linting
jobs:
    ruff:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
            - uses: astral-sh/ruff-action@c6bea5606c33b5d04902374392d9233464b90660  # v3.3.0
