name: Translation validation
on:
    push:
        paths:
            - 'archinstall/**/*.py'
            - 'archinstall/locales/**'
            - '.github/workflows/translation-check.yaml'
    pull_request:
        paths:
            - 'archinstall/**/*.py'
            - 'archinstall/locales/**'
            - '.github/workflows/translation-check.yaml'
jobs:
    translations:
        name: Validate translations
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
            - name: Install gettext
              run: sudo apt-get update && sudo apt-get install -y gettext
            - name: Run translation checks
              run: bash archinstall/locales/locales_generator.sh check
