name: Translation validation
on:
    push:
        paths:
            - 'archinstall/**/*.py'
            - 'archinstall/locales/**'
            - '.github/workflows/translation-check.yaml'
    pull_request:
        paths:
            - 'archinstall/**/*.py'
            - 'archinstall/locales/**'
            - '.github/workflows/translation-check.yaml'
jobs:
    translations:
        name: Validate translations
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
            - name: Install gettext
              run: sudo apt-get update && sudo apt-get install -y gettext
            - name: Run translation checks
              run: bash archinstall/locales/locales_generator.sh check
